spring.application.name=notification
spring.config.import=optional:configserver:${MAIN_HOST}:${PORT_CENTRAL_CONFIG}

# send mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_ADMIN_USERNAME}
spring.mail.password=${MAIL_ADMIN_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true