management.endpoints.web.exposure.include=health,info

# service urls
url.central-config=${MAIN_HOST}:${PORT_CENTRAL_CONFIG}
url.gateway=${MAIN_HOST}:${PORT_GATEWAY}
url.auth-server=${MAIN_HOST}:${PORT_AUTH_SERVER}