management.endpoints.web.exposure.include=health,info

# service urls
url.gateway=${MAIN_HOST}:${PORT_GATEWAY}
url.auth-server=${MAIN_HOST}:${PORT_AUTH_SERVER}

# connect to discovery server
eureka.client.service-url.defaultZone=${MAIN_HOST}:${PORT_DISCOVERY}/eureka/
eureka.instance.prefer-ip-address=true
