server.port=${PORT_AUTH_SERVER}

# oauth2 login
spring.security.oauth2.client.registration.google.client-id=${sec.oauth2.google.client-id}
spring.security.oauth2.client.registration.google.client-secret=${sec.oauth2.google.client-secret}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${url.auth-server}/login/oauth2/code/google

# retry
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=3000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.1
spring.cloud.config.fail-fast=true