server.port=${PORT_DISCOVERY}

# retry
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=3000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.1
spring.cloud.config.fail-fast=true